// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Returned by `POST /api/invitations/:id/accept` — confirms team join.
 */
export type AcceptInvitationResponse = { team_id: string, role: string, };
