// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request body for `POST /api/teams/:id/members` — add a member by nickname.
 */
export type AddMemberRequest = { nickname: string, };
