// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Legacy JSON error shape `{ "error": "..." }` returned by all error responses.
 */
export type ApiError = { error: string, };
