// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Returned on successful login / register / refresh.
 */
export type AuthTokenResponse = { access_token: string, refresh_token: string, expires_in: bigint, user_id: string, nickname: string, };
