// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OAuthProviderInfo } from "./OAuthProviderInfo";

/**
 * Available auth providers (returned by GET /api/auth/providers).
 */
export type AuthProvidersResponse = { email_password: boolean, oauth: Array<OAuthProviderInfo>, };
