// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Email + password registration.
 */
export type AuthRegisterRequest = { email: string, password: string, nickname: string, };
