// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Change password request.
 */
export type ChangePasswordRequest = { current_password: string, new_password: string, };
