// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SyncedPrivacyConfig } from "./SyncedPrivacyConfig";
import type { SyncedWatcherConfig } from "./SyncedWatcherConfig";

/**
 * Team-level configuration synced to CLI clients.
 */
export type ConfigSyncResponse = { privacy: SyncedPrivacyConfig | null, watchers: SyncedWatcherConfig | null, };
