// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreateGroupRequest = { name: string, description: string | null, is_public: boolean, };
