// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request body for `POST /api/teams` — create a new team.
 */
export type CreateTeamRequest = { name: string, description: string | null, is_public: boolean | null, };
