// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Returned by `GET /api/health` — server liveness check.
 */
export type HealthResponse = { status: string, version: string, };
