// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Single invitation record returned by list and detail endpoints.
 */
export type InvitationResponse = { id: string, team_id: string, team_name: string, email: string | null, oauth_provider: string | null, oauth_provider_username: string | null, invited_by_nickname: string, role: string, status: string, created_at: string, };
