// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request body for `POST /api/teams/:id/invite` — invite a user by email or OAuth identity.
 */
export type InviteRequest = { email: string | null, 
/**
 * OAuth provider name (e.g., "github", "gitlab").
 */
oauth_provider: string | null, 
/**
 * Username on the OAuth provider (e.g., "octocat").
 */
oauth_provider_username: string | null, role: string | null, };
