// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type InviteResponse = { id: string, group_id: string, code: string, max_uses: bigint | null, used_count: bigint, expires_at: string | null, created_at: string, };
