// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A linked OAuth provider shown in user settings.
 */
export type LinkedProvider = { provider: string, provider_username: string, display_name: string, };
