// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InvitationResponse } from "./InvitationResponse";

/**
 * Returned by `GET /api/invitations` — pending invitations for the current user.
 */
export type ListInvitationsResponse = { invitations: Array<InvitationResponse>, };
