// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TeamResponse } from "./TeamResponse";

/**
 * Returned by `GET /api/teams` — teams the authenticated user belongs to.
 */
export type ListTeamsResponse = { teams: Array<TeamResponse>, };
