// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Email + password login.
 */
export type LoginRequest = { email: string, password: string, };
