// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Logout request (invalidate refresh token).
 */
export type LogoutRequest = { refresh_token: string, };
