// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Public info about an OAuth provider.
 */
export type OAuthProviderInfo = { id: string, display_name: string, };
