// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Generic success response for operations that don't return data.
 */
export type OkResponse = { ok: boolean, };
