// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Refresh token request.
 */
export type RefreshRequest = { refresh_token: string, };
