// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Legacy register (nickname-only). Kept for backward compatibility with CLI.
 */
export type RegisterRequest = { nickname: string, };
