// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Returned on successful legacy register (nickname-only, CLI-compatible).
 */
export type RegisterResponse = { user_id: string, nickname: string, api_key: string, };
