// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A link between two sessions (e.g., handoff chain).
 */
export type SessionLink = { session_id: string, linked_session_id: string, link_type: string, created_at: string, };
