// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Query parameters for `GET /api/sessions` — pagination, filtering, sorting.
 */
export type SessionListQuery = { page: number, per_page: number, search: string | null, tool: string | null, team_id: string | null, 
/**
 * Sort order: "recent" (default), "popular" (message_count desc), "longest"
 */
sort: string | null, 
/**
 * Time range filter: "24h", "7d", "30d", "all" (default)
 */
time_range: string | null, };
