// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionLink } from "./SessionLink";

/**
 * Single session detail returned by `GET /api/sessions/:id`.
 */
export type SessionDetail = { team_name: string | null, linked_sessions?: Array<SessionLink>, id: string, user_id: string | null, nickname: string | null, team_id: string, tool: string, agent_provider: string | null, agent_model: string | null, title: string | null, description: string | null, 
/**
 * Comma-separated tags string
 */
tags: string | null, created_at: string, uploaded_at: string, message_count: bigint, task_count: bigint, event_count: bigint, duration_seconds: bigint, total_input_tokens: bigint, total_output_tokens: bigint, git_remote?: string | null, git_branch?: string | null, git_commit?: string | null, git_repo_name?: string | null, pr_number?: bigint | null, pr_url?: string | null, working_directory?: string | null, files_modified?: string | null, files_read?: string | null, has_errors: boolean, };
