// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionSummary } from "./SessionSummary";

/**
 * Paginated session listing returned by `GET /api/sessions`.
 */
export type SessionListResponse = { sessions: Array<SessionSummary>, total: bigint, page: number, per_page: number, };
