// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request body for `POST /api/sessions/:id/events` — append live events.
 */
export type StreamEventsRequest = { agent: any, context: any, events: any[], };
