// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Returned by `POST /api/sessions/:id/events` — number of events accepted.
 */
export type StreamEventsResponse = { accepted: number, };
