// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Privacy settings synced from the team — controls what data is recorded.
 */
export type SyncedPrivacyConfig = { exclude_patterns: Array<string> | null, exclude_tools: Array<string> | null, };
