// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Watcher toggle settings synced from the team — which tools to monitor.
 */
export type SyncedWatcherConfig = { claude_code: boolean | null, opencode: boolean | null, cursor: boolean | null, };
