// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Aggregate totals across all sessions in a team.
 */
export type TeamStatsTotals = { session_count: bigint, message_count: bigint, event_count: bigint, tool_call_count: bigint, duration_seconds: bigint, total_input_tokens: bigint, total_output_tokens: bigint, };
