// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Query parameters for `GET /api/teams/:id/stats`.
 */
export type TeamStatsQuery = { 
/**
 * Time range filter: "24h", "7d", "30d", "all" (default)
 */
time_range: string | null, };
