// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TeamStatsTotals } from "./TeamStatsTotals";
import type { ToolStats } from "./ToolStats";
import type { UserStats } from "./UserStats";

/**
 * Returned by `GET /api/teams/:id/stats` — aggregated team statistics.
 */
export type TeamStatsResponse = { team_id: string, time_range: string, totals: TeamStatsTotals, by_user: Array<UserStats>, by_tool: Array<ToolStats>, };
