// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionSummary } from "./SessionSummary";

/**
 * Returned by `GET /api/teams/:id` — team info with member count and recent sessions.
 */
export type TeamDetailResponse = { member_count: bigint, sessions: Array<SessionSummary>, id: string, name: string, description: string | null, is_public: boolean, created_by: string, created_at: string, };
