// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Single team record returned by list and detail endpoints.
 */
export type TeamResponse = { id: string, name: string, description: string | null, is_public: boolean, created_by: string, created_at: string, };
