// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request body for `PUT /api/teams/:id` — partial team update.
 */
export type UpdateTeamRequest = { name: string | null, description: string | null, is_public: boolean | null, };
