// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request body for `POST /api/sessions` — upload a recorded session.
 */
export type UploadRequest = { session: any, team_id: string | null, body_url?: string | null, linked_session_ids?: Array<string> | null, git_remote?: string | null, git_branch?: string | null, git_commit?: string | null, git_repo_name?: string | null, pr_number?: bigint | null, pr_url?: string | null, };
