// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Returned on successful session upload — contains the new session ID and URL.
 */
export type UploadResponse = { id: string, url: string, };
