// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-user aggregated statistics within a team.
 */
export type UserStats = { user_id: string, nickname: string, session_count: bigint, message_count: bigint, event_count: bigint, duration_seconds: bigint, total_input_tokens: bigint, total_output_tokens: bigint, };
