// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LinkedProvider } from "./LinkedProvider";

/**
 * Full user profile returned by `GET /api/auth/me`.
 */
export type UserSettingsResponse = { user_id: string, nickname: string, api_key: string, created_at: string, email: string | null, avatar_url: string | null,
/**
 * Linked OAuth providers (generic — replaces github_username)
 */
oauth_providers: Array<LinkedProvider>, 
/**
 * Legacy: GitHub username (populated from oauth_providers for backward compat)
 */
github_username: string | null, };
