// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Returned by `POST /api/auth/verify` — confirms token validity.
 */
export type VerifyResponse = { user_id: string, nickname: string, };
