// AUTO-GENERATED by opensession-api-types — DO NOT EDIT
// Regenerate with: cargo test -p opensession-api-types -- export_typescript

export interface RegisterRequest { nickname: string, }

export interface RegisterResponse { user_id: string, nickname: string, api_key: string, }

export interface VerifyResponse { user_id: string, nickname: string, }

export interface UserSettingsResponse { user_id: string, nickname: string, api_key: string, github_login: string | null, avatar_url: string | null, created_at: string, }

export interface UploadResponse { id: string, url: string, }

export interface SessionSummary { id: string, user_id: string | null, nickname: string | null, tool: string, agent_provider: string | null, agent_model: string | null, title: string | null, description: string | null, 
/**
 * Comma-separated tags string
 */
tags: string | null, visibility: string, created_at: string, uploaded_at: string, message_count: number, task_count: number, event_count: number, duration_seconds: number, avatar_url: string | null, }

export interface SessionListResponse { sessions: Array<SessionSummary>, total: number, page: number, per_page: number, }

export interface SessionListQuery { page: number, per_page: number, search: string | null, tool: string | null, group_id: string | null, 
/**
 * Sort order: "recent" (default), "popular" (message_count desc), "longest"
 */
sort: string | null, 
/**
 * Time range filter: "24h", "7d", "30d", "all" (default)
 */
time_range: string | null, }

export interface SessionDetail { groups: Array<GroupRef>, id: string, user_id: string | null, nickname: string | null, tool: string, agent_provider: string | null, agent_model: string | null, title: string | null, description: string | null, 
/**
 * Comma-separated tags string
 */
tags: string | null, visibility: string, created_at: string, uploaded_at: string, message_count: number, task_count: number, event_count: number, duration_seconds: number, avatar_url: string | null, }

export interface GroupRef { id: string, name: string, }

export interface CreateGroupRequest { name: string, description: string | null, is_public: boolean, }

export interface GroupResponse { id: string, name: string, description: string | null, is_public: boolean, owner_id: string, created_at: string, }

export interface ListGroupsResponse { groups: Array<GroupResponse>, }

export interface GroupDetailResponse { member_count: number, sessions: Array<SessionSummary>, id: string, name: string, description: string | null, is_public: boolean, owner_id: string, created_at: string, }

export interface UpdateGroupRequest { name: string | null, description: string | null, is_public: boolean | null, }

export interface CreateInviteRequest { max_uses: number | null, expires_at: string | null, }

export interface InviteResponse { id: string, group_id: string, code: string, max_uses: number | null, used_count: number, expires_at: string | null, created_at: string, }

export interface JoinResponse { group_id: string, group_name: string, }

export interface MemberResponse { user_id: string, nickname: string, role: string, joined_at: string, }

export interface ListMembersResponse { members: Array<MemberResponse>, }

export interface HealthResponse { status: string, version: string, }

export interface ApiError { error: string, }
