// AUTO-GENERATED by opensession-api — DO NOT EDIT
// Regenerate with: cargo test -p opensession-api -- export_typescript

export type TeamRole = 'admin' | 'member';

export type InvitationStatus = 'pending' | 'accepted' | 'declined';

export type SortOrder = 'recent' | 'popular' | 'longest';

export type TimeRange = '24h' | '7d' | '30d' | 'all';

export type LinkType = 'handoff' | 'related' | 'parent' | 'child';

export interface RegisterRequest {
	nickname: string;
}

export interface AuthRegisterRequest {
	email: string;
	password: string;
	nickname: string;
}

export interface LoginRequest {
	email: string;
	password: string;
}

export interface AuthTokenResponse {
	access_token: string;
	refresh_token: string;
	expires_in: number;
	user_id: string;
	nickname: string;
}

export interface RefreshRequest {
	refresh_token: string;
}

export interface LogoutRequest {
	refresh_token: string;
}

export interface ChangePasswordRequest {
	current_password: string;
	new_password: string;
}

export interface RegisterResponse {
	user_id: string;
	nickname: string;
	api_key: string;
}

export interface VerifyResponse {
	user_id: string;
	nickname: string;
}

export interface UserSettingsResponse {
	user_id: string;
	nickname: string;
	api_key: string;
	created_at: string;
	email: string | null;
	avatar_url: string | null;
	/**
	 * Linked OAuth providers (generic — replaces github_username)
	 */
	oauth_providers: Array<LinkedProvider>;
	/**
	 * Legacy: GitHub username (populated from oauth_providers for backward compat)
	 */
	github_username: string | null;
}

export interface OkResponse {
	ok: boolean;
}

export interface RegenerateKeyResponse {
	api_key: string;
}

export interface OAuthLinkResponse {
	url: string;
}

export interface UploadResponse {
	id: string;
	url: string;
}

export interface SessionSummary {
	id: string;
	user_id: string | null;
	nickname: string | null;
	team_id: string;
	tool: string;
	agent_provider: string | null;
	agent_model: string | null;
	title: string | null;
	description: string | null;
	/**
	 * Comma-separated tags string
	 */
	tags: string | null;
	created_at: string;
	uploaded_at: string;
	message_count: number;
	task_count: number;
	event_count: number;
	duration_seconds: number;
	total_input_tokens: number;
	total_output_tokens: number;
	git_remote?: string | null;
	git_branch?: string | null;
	git_commit?: string | null;
	git_repo_name?: string | null;
	pr_number?: number | null;
	pr_url?: string | null;
	working_directory?: string | null;
	files_modified?: string | null;
	files_read?: string | null;
	has_errors: boolean;
}

export interface SessionListResponse {
	sessions: Array<SessionSummary>;
	total: number;
	page: number;
	per_page: number;
}

export interface SessionListQuery {
	page: number;
	per_page: number;
	search: string | null;
	tool: string | null;
	team_id: string | null;
	/**
	 * Sort order (default: recent)
	 */
	sort: SortOrder | null;
	/**
	 * Time range filter (default: all)
	 */
	time_range: TimeRange | null;
}

export interface SessionDetail {
	team_name: string | null;
	linked_sessions?: Array<SessionLink>;
	id: string;
	user_id: string | null;
	nickname: string | null;
	team_id: string;
	tool: string;
	agent_provider: string | null;
	agent_model: string | null;
	title: string | null;
	description: string | null;
	/**
	 * Comma-separated tags string
	 */
	tags: string | null;
	created_at: string;
	uploaded_at: string;
	message_count: number;
	task_count: number;
	event_count: number;
	duration_seconds: number;
	total_input_tokens: number;
	total_output_tokens: number;
	git_remote?: string | null;
	git_branch?: string | null;
	git_commit?: string | null;
	git_repo_name?: string | null;
	pr_number?: number | null;
	pr_url?: string | null;
	working_directory?: string | null;
	files_modified?: string | null;
	files_read?: string | null;
	has_errors: boolean;
}

export interface SessionLink {
	session_id: string;
	linked_session_id: string;
	link_type: LinkType;
	created_at: string;
}

export interface CreateTeamRequest {
	name: string;
	description: string | null;
	is_public: boolean | null;
}

export interface TeamResponse {
	id: string;
	name: string;
	description: string | null;
	is_public: boolean;
	created_by: string;
	created_at: string;
}

export interface ListTeamsResponse {
	teams: Array<TeamResponse>;
}

export interface TeamDetailResponse {
	member_count: number;
	sessions: Array<SessionSummary>;
	id: string;
	name: string;
	description: string | null;
	is_public: boolean;
	created_by: string;
	created_at: string;
}

export interface UpdateTeamRequest {
	name: string | null;
	description: string | null;
	is_public: boolean | null;
}

export interface TeamStatsQuery {
	/**
	 * Time range filter (default: all)
	 */
	time_range: TimeRange | null;
}

export interface TeamStatsResponse {
	team_id: string;
	time_range: TimeRange;
	totals: TeamStatsTotals;
	by_user: Array<UserStats>;
	by_tool: Array<ToolStats>;
}

export interface TeamStatsTotals {
	session_count: number;
	message_count: number;
	event_count: number;
	tool_call_count: number;
	duration_seconds: number;
	total_input_tokens: number;
	total_output_tokens: number;
}

export interface UserStats {
	user_id: string;
	nickname: string;
	session_count: number;
	message_count: number;
	event_count: number;
	duration_seconds: number;
	total_input_tokens: number;
	total_output_tokens: number;
}

export interface ToolStats {
	tool: string;
	session_count: number;
	message_count: number;
	event_count: number;
	duration_seconds: number;
	total_input_tokens: number;
	total_output_tokens: number;
}

export interface AddMemberRequest {
	nickname: string;
}

export interface MemberResponse {
	user_id: string;
	nickname: string;
	role: TeamRole;
	joined_at: string;
}

export interface ListMembersResponse {
	members: Array<MemberResponse>;
}

export interface InviteRequest {
	email: string | null;
	/**
	 * OAuth provider name (e.g., "github", "gitlab").
	 */
	oauth_provider: string | null;
	/**
	 * Username on the OAuth provider (e.g., "octocat").
	 */
	oauth_provider_username: string | null;
	role: TeamRole | null;
}

export interface InvitationResponse {
	id: string;
	team_id: string;
	team_name: string;
	email: string | null;
	oauth_provider: string | null;
	oauth_provider_username: string | null;
	invited_by_nickname: string;
	role: TeamRole;
	status: InvitationStatus;
	created_at: string;
}

export interface ListInvitationsResponse {
	invitations: Array<InvitationResponse>;
}

export interface AcceptInvitationResponse {
	team_id: string;
	role: TeamRole;
}

export interface AuthProvidersResponse {
	email_password: boolean;
	oauth: Array<OAuthProviderInfo>;
}

export interface OAuthProviderInfo {
	id: string;
	display_name: string;
}

export interface LinkedProvider {
	provider: string;
	provider_username: string;
	display_name: string;
}

export interface HealthResponse {
	status: string;
	version: string;
}

export interface ApiError {
	error: string;
}
