// AUTO-GENERATED by opensession-api — DO NOT EDIT
// Regenerate with: cargo test -p opensession-api -- export_typescript

export type SortOrder = "recent" | "popular" | "longest"

export type TimeRange = "24h" | "7d" | "30d" | "all"

export type LinkType = "handoff" | "related" | "parent" | "child"

export interface AuthRegisterRequest { email: string, password: string, nickname: string, }

export interface LoginRequest { email: string, password: string, }

export interface AuthTokenResponse { access_token: string, refresh_token: string, expires_in: number, user_id: string, nickname: string, }

export interface RefreshRequest { refresh_token: string, }

export interface LogoutRequest { refresh_token: string, }

export interface ChangePasswordRequest { current_password: string, new_password: string, }

export interface VerifyResponse { user_id: string, nickname: string, }

export interface UserSettingsResponse { user_id: string, nickname: string, created_at: string, email: string | null, avatar_url: string | null, 
/**
 * Linked OAuth providers.
 */
oauth_providers: Array<LinkedProvider>, }

export interface OkResponse { ok: boolean, }

export interface IssueApiKeyResponse { api_key: string, }

export interface GitCredentialSummary { id: string, label: string, host: string, path_prefix: string, header_name: string, created_at: string, updated_at: string, last_used_at: string | null, }

export interface ListGitCredentialsResponse { credentials: Array<GitCredentialSummary>, }

export interface CreateGitCredentialRequest { label: string, host: string, path_prefix?: string | null, header_name: string, header_value: string, }

export interface OAuthLinkResponse { url: string, }

export interface UploadResponse { id: string, url: string, session_score: number, score_plugin: string, }

export interface SessionSummary { id: string, user_id: string | null, nickname: string | null, tool: string, agent_provider: string | null, agent_model: string | null, title: string | null, description: string | null, 
/**
 * Comma-separated tags string
 */
tags: string | null, created_at: string, uploaded_at: string, message_count: number, task_count: number, event_count: number, duration_seconds: number, total_input_tokens: number, total_output_tokens: number, git_remote?: string | null, git_branch?: string | null, git_commit?: string | null, git_repo_name?: string | null, pr_number?: number | null, pr_url?: string | null, working_directory?: string | null, files_modified?: string | null, files_read?: string | null, has_errors: boolean, max_active_agents: number, session_score: number, score_plugin: string, }

export interface SessionListResponse { sessions: Array<SessionSummary>, total: number, page: number, per_page: number, }

export interface SessionListQuery { page: number, per_page: number, search: string | null, tool: string | null, git_repo_name: string | null, 
/**
 * Sort order (default: recent)
 */
sort: SortOrder | null, 
/**
 * Time range filter (default: all)
 */
time_range: TimeRange | null, }

export interface DesktopSessionListQuery { page: string | null, per_page: string | null, search: string | null, tool: string | null, git_repo_name: string | null, sort: string | null, time_range: string | null, }

export interface SessionRepoListResponse { repos: Array<string>, }

export interface DesktopHandoffBuildRequest { session_id: string, pin_latest: boolean, }

export interface DesktopHandoffBuildResponse { artifact_uri: string, pinned_alias?: string | null, download_file_name?: string | null, download_content?: string | null, }

export interface DesktopContractVersionResponse { version: string, }

export type DesktopSummaryProviderId = "disabled" | "ollama" | "codex_exec" | "claude_cli"

export type DesktopSummaryProviderTransport = "none" | "cli" | "http"

export type DesktopSummarySourceMode = "session_only" | "session_or_git_changes"

export type DesktopSummaryResponseStyle = "compact" | "standard" | "detailed"

export type DesktopSummaryOutputShape = "layered" | "file_list" | "security_first"

export type DesktopSummaryTriggerMode = "manual" | "on_session_save"

export type DesktopSummaryStorageBackend = "hidden_ref" | "local_db" | "none"

export interface DesktopRuntimeSummaryProviderSettings { id: DesktopSummaryProviderId, transport: DesktopSummaryProviderTransport, endpoint: string, model: string, }

export interface DesktopRuntimeSummaryPromptSettings { template: string, default_template: string, }

export interface DesktopRuntimeSummaryResponseSettings { style: DesktopSummaryResponseStyle, shape: DesktopSummaryOutputShape, }

export interface DesktopRuntimeSummaryStorageSettings { trigger: DesktopSummaryTriggerMode, backend: DesktopSummaryStorageBackend, }

export interface DesktopRuntimeSummarySettings { provider: DesktopRuntimeSummaryProviderSettings, prompt: DesktopRuntimeSummaryPromptSettings, response: DesktopRuntimeSummaryResponseSettings, storage: DesktopRuntimeSummaryStorageSettings, source_mode: DesktopSummarySourceMode, }

export interface DesktopRuntimeSummaryProviderSettingsUpdate { id: DesktopSummaryProviderId, endpoint: string, model: string, }

export interface DesktopRuntimeSummaryPromptSettingsUpdate { template: string, }

export interface DesktopRuntimeSummaryResponseSettingsUpdate { style: DesktopSummaryResponseStyle, shape: DesktopSummaryOutputShape, }

export interface DesktopRuntimeSummaryStorageSettingsUpdate { trigger: DesktopSummaryTriggerMode, backend: DesktopSummaryStorageBackend, }

export interface DesktopRuntimeSummarySettingsUpdate { provider: DesktopRuntimeSummaryProviderSettingsUpdate, prompt: DesktopRuntimeSummaryPromptSettingsUpdate, response: DesktopRuntimeSummaryResponseSettingsUpdate, storage: DesktopRuntimeSummaryStorageSettingsUpdate, source_mode: DesktopSummarySourceMode, }

export interface DesktopRuntimeSummaryUiConstraints { source_mode_locked: boolean, source_mode_locked_value: DesktopSummarySourceMode, }

export type DesktopVectorSearchProvider = "ollama"

export type DesktopVectorSearchGranularity = "event_line_chunk"

export type DesktopVectorInstallState = "not_installed" | "installing" | "ready" | "failed"

export type DesktopVectorIndexState = "idle" | "running" | "complete" | "failed"

export interface DesktopRuntimeVectorSearchSettings { enabled: boolean, provider: DesktopVectorSearchProvider, model: string, endpoint: string, granularity: DesktopVectorSearchGranularity, chunk_size_lines: number, chunk_overlap_lines: number, top_k_chunks: number, top_k_sessions: number, }

export interface DesktopRuntimeVectorSearchSettingsUpdate { enabled: boolean, provider: DesktopVectorSearchProvider, model: string, endpoint: string, granularity: DesktopVectorSearchGranularity, chunk_size_lines: number, chunk_overlap_lines: number, top_k_chunks: number, top_k_sessions: number, }

export interface DesktopVectorPreflightResponse { provider: DesktopVectorSearchProvider, endpoint: string, model: string, ollama_reachable: boolean, model_installed: boolean, install_state: DesktopVectorInstallState, progress_pct: number, message?: string | null, }

export interface DesktopVectorInstallStatusResponse { state: DesktopVectorInstallState, model: string, progress_pct: number, message?: string | null, }

export interface DesktopVectorIndexStatusResponse { state: DesktopVectorIndexState, processed_sessions: number, total_sessions: number, message?: string | null, started_at?: string | null, finished_at?: string | null, }

export interface DesktopVectorSessionMatch { session: SessionSummary, score: number, chunk_id: string, start_line: number, end_line: number, snippet: string, }

export interface DesktopVectorSearchResponse { query: string, sessions: Array<DesktopVectorSessionMatch>, next_cursor?: string | null, total_candidates: number, }

export interface DesktopRuntimeSettingsResponse { session_default_view: string, summary: DesktopRuntimeSummarySettings, vector_search: DesktopRuntimeVectorSearchSettings, ui_constraints: DesktopRuntimeSummaryUiConstraints, }

export interface DesktopRuntimeSettingsUpdateRequest { session_default_view?: string | null, summary?: DesktopRuntimeSummarySettingsUpdate | null, vector_search?: DesktopRuntimeVectorSearchSettingsUpdate | null, }

export interface DesktopSummaryProviderDetectResponse { detected: boolean, provider?: DesktopSummaryProviderId | null, transport?: DesktopSummaryProviderTransport | null, model?: string | null, endpoint?: string | null, }

export interface DesktopSessionSummaryResponse { session_id: string, summary?: any, source_details?: any, diff_tree: any[], source_kind?: string | null, generation_kind?: string | null, error?: string | null, }

export interface DesktopApiError { code: string, status: number, message: string, details?: Record<string, any> | null, }

export interface SessionDetail { linked_sessions?: Array<SessionLink>, id: string, user_id: string | null, nickname: string | null, tool: string, agent_provider: string | null, agent_model: string | null, title: string | null, description: string | null, 
/**
 * Comma-separated tags string
 */
tags: string | null, created_at: string, uploaded_at: string, message_count: number, task_count: number, event_count: number, duration_seconds: number, total_input_tokens: number, total_output_tokens: number, git_remote?: string | null, git_branch?: string | null, git_commit?: string | null, git_repo_name?: string | null, pr_number?: number | null, pr_url?: string | null, working_directory?: string | null, files_modified?: string | null, files_read?: string | null, has_errors: boolean, max_active_agents: number, session_score: number, score_plugin: string, }

export interface SessionLink { session_id: string, linked_session_id: string, link_type: LinkType, created_at: string, }

export type ParseSource = { "kind": "git", remote: string, ref: string, path: string, } | { "kind": "github", owner: string, repo: string, ref: string, path: string, } | { "kind": "inline", filename: string, 
/**
 * Base64-encoded UTF-8 text content.
 */
content_base64: string, }

export interface ParseCandidate { id: string, confidence: number, reason: string, }

export interface ParsePreviewRequest { source: ParseSource, parser_hint?: string | null, }

export interface ParsePreviewResponse { parser_used: string, parser_candidates: Array<ParseCandidate>, session: any, source: ParseSource, warnings: Array<string>, native_adapter?: string | null, }

export interface ParsePreviewErrorResponse { code: string, message: string, parser_candidates?: Array<ParseCandidate>, }

export interface LocalReviewBundle { review_id: string, generated_at: string, pr: LocalReviewPrMeta, commits: Array<LocalReviewCommit>, sessions: Array<LocalReviewSession>, }

export interface LocalReviewPrMeta { url: string, owner: string, repo: string, number: number, remote: string, base_sha: string, head_sha: string, }

export interface LocalReviewReviewerQa { question: string, answer?: string | null, }

export interface LocalReviewReviewerDigest { qa: Array<LocalReviewReviewerQa>, modified_files: Array<string>, test_files: Array<string>, }

export interface LocalReviewCommit { sha: string, title: string, author_name: string, author_email: string, authored_at: string, session_ids: Array<string>, reviewer_digest: LocalReviewReviewerDigest, semantic_summary?: LocalReviewSemanticSummary | null, }

export interface LocalReviewLayerFileChange { layer: string, summary: string, files: Array<string>, }

export interface LocalReviewSemanticSummary { changes: string, auth_security: string, layer_file_changes: Array<LocalReviewLayerFileChange>, source_kind: string, generation_kind: string, provider: string, model?: string | null, error?: string | null, diff_tree: any[], }

export interface LocalReviewSession { session_id: string, ledger_ref: string, hail_path: string, commit_shas: Array<string>, session: any, }

export interface AuthProvidersResponse { email_password: boolean, oauth: Array<OAuthProviderInfo>, }

export interface OAuthProviderInfo { id: string, display_name: string, }

export interface LinkedProvider { provider: string, provider_username: string, display_name: string, }

export interface HealthResponse { status: string, version: string, }

export interface CapabilitiesResponse { auth_enabled: boolean, parse_preview_enabled: boolean, register_targets: Array<string>, share_modes: Array<string>, }

export interface ApiError { code: string, message: string, }
