// AUTO-GENERATED by opensession-api — DO NOT EDIT
// Regenerate with: cargo test -p opensession-api -- export_typescript

export type SortOrder = "recent" | "popular" | "longest"

export type TimeRange = "24h" | "7d" | "30d" | "all"

export type LinkType = "handoff" | "related" | "parent" | "child"

export interface AuthRegisterRequest { email: string, password: string, nickname: string, }

export interface LoginRequest { email: string, password: string, }

export interface AuthTokenResponse { access_token: string, refresh_token: string, expires_in: number, user_id: string, nickname: string, }

export interface RefreshRequest { refresh_token: string, }

export interface LogoutRequest { refresh_token: string, }

export interface ChangePasswordRequest { current_password: string, new_password: string, }

export interface VerifyResponse { user_id: string, nickname: string, }

export interface UserSettingsResponse { user_id: string, nickname: string, created_at: string, email: string | null, avatar_url: string | null, 
/**
 * Linked OAuth providers.
 */
oauth_providers: Array<LinkedProvider>, }

export interface OkResponse { ok: boolean, }

export interface IssueApiKeyResponse { api_key: string, }

export interface OAuthLinkResponse { url: string, }

export interface UploadResponse { id: string, url: string, session_score: number, score_plugin: string, }

export interface SessionSummary { id: string, user_id: string | null, nickname: string | null, tool: string, agent_provider: string | null, agent_model: string | null, title: string | null, description: string | null, 
/**
 * Comma-separated tags string
 */
tags: string | null, created_at: string, uploaded_at: string, message_count: number, task_count: number, event_count: number, duration_seconds: number, total_input_tokens: number, total_output_tokens: number, git_remote?: string | null, git_branch?: string | null, git_commit?: string | null, git_repo_name?: string | null, pr_number?: number | null, pr_url?: string | null, working_directory?: string | null, files_modified?: string | null, files_read?: string | null, has_errors: boolean, max_active_agents: number, session_score: number, score_plugin: string, }

export interface SessionListResponse { sessions: Array<SessionSummary>, total: number, page: number, per_page: number, }

export interface SessionListQuery { page: number, per_page: number, search: string | null, tool: string | null, 
/**
 * Sort order (default: recent)
 */
sort: SortOrder | null, 
/**
 * Time range filter (default: all)
 */
time_range: TimeRange | null, }

export interface SessionDetail { linked_sessions?: Array<SessionLink>, id: string, user_id: string | null, nickname: string | null, tool: string, agent_provider: string | null, agent_model: string | null, title: string | null, description: string | null, 
/**
 * Comma-separated tags string
 */
tags: string | null, created_at: string, uploaded_at: string, message_count: number, task_count: number, event_count: number, duration_seconds: number, total_input_tokens: number, total_output_tokens: number, git_remote?: string | null, git_branch?: string | null, git_commit?: string | null, git_repo_name?: string | null, pr_number?: number | null, pr_url?: string | null, working_directory?: string | null, files_modified?: string | null, files_read?: string | null, has_errors: boolean, max_active_agents: number, session_score: number, score_plugin: string, }

export interface SessionLink { session_id: string, linked_session_id: string, link_type: LinkType, created_at: string, }

export type ParseSource = { "kind": "git", remote: string, ref: string, path: string, } | { "kind": "github", owner: string, repo: string, ref: string, path: string, } | { "kind": "inline", filename: string, 
/**
 * Base64-encoded UTF-8 text content.
 */
content_base64: string, }

export interface ParseCandidate { id: string, confidence: number, reason: string, }

export interface ParsePreviewRequest { source: ParseSource, parser_hint?: string | null, }

export interface ParsePreviewResponse { parser_used: string, parser_candidates: Array<ParseCandidate>, session: any, source: ParseSource, warnings: Array<string>, native_adapter?: string | null, }

export interface ParsePreviewErrorResponse { code: string, message: string, parser_candidates?: Array<ParseCandidate>, }

export interface AuthProvidersResponse { email_password: boolean, oauth: Array<OAuthProviderInfo>, }

export interface OAuthProviderInfo { id: string, display_name: string, }

export interface LinkedProvider { provider: string, provider_username: string, display_name: string, }

export interface HealthResponse { status: string, version: string, }

export interface CapabilitiesResponse { auth_enabled: boolean, upload_enabled: boolean, ingest_preview_enabled: boolean, gh_share_enabled: boolean, }

export interface ApiError { code: string, message: string, }
