// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreateInviteRequest = { max_uses: bigint | null, expires_at: string | null, };
