// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionSummary } from "./SessionSummary";

export type GroupDetailResponse = { member_count: bigint, sessions: Array<SessionSummary>, id: string, name: string, description: string | null, is_public: boolean, owner_id: string, created_at: string, };
