// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MemberResponse = { user_id: string, nickname: string, role: string, joined_at: string, };
