// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GroupRef } from "./GroupRef";

export type SessionDetail = { groups: Array<GroupRef>, id: string, user_id: string | null, nickname: string | null, tool: string, agent_provider: string | null, agent_model: string | null, title: string | null, description: string | null, 
/**
 * Comma-separated tags string
 */
tags: string | null, visibility: string, created_at: string, uploaded_at: string, message_count: bigint, task_count: bigint, event_count: bigint, duration_seconds: bigint, avatar_url: string | null, };
