// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Flat session summary returned by list/detail endpoints.
 * This is NOT the full HAIL Session — it's a DB-derived summary.
 */
export type SessionSummary = { id: string, user_id: string | null, nickname: string | null, tool: string, agent_provider: string | null, agent_model: string | null, title: string | null, description: string | null, 
/**
 * Comma-separated tags string
 */
tags: string | null, visibility: string, created_at: string, uploaded_at: string, message_count: bigint, task_count: bigint, event_count: bigint, duration_seconds: bigint, avatar_url: string | null, };
