// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UploadRequest = { session: any, visibility: string | null, group_ids: Array<string>, };
