// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UserSettingsResponse = { user_id: string, nickname: string, api_key: string, github_login: string | null, avatar_url: string | null, created_at: string, };
